name: 'Deploy to Cloud Storage'
description: 'Deploy to Cloud Storage'
inputs:
  bucket:
    description: 'GCP Bucket Name'
    required: true
  dist-folder:
    description: 'Folder to deploy'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GOOGLE_KEY: ${{ secrets.GCP_SA_KEY }}
