name: 'Deploy to Cloud Storage'
description: 'Deploy to Cloud Storage'
inputs:
  bucket:
    description: 'GCP Bucket Name'
    required: true
  dist-folder:
    description: 'Folder to deploy'
    required: true
  gcp-sa-key:
    description: 'GCP Service Account Key'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '--GOOGLE_KEY'
    - ${{ inputs.gcp-sa-key }}
